# Generated by Django 4.2.5 on 2023-10-31 10:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "phoneNum",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            django.core.validators.RegexValidator(
                                message="Phone number entered is invalid",
                                regex="^[89]\\d{7}$",
                            ),
                        ],
                    ),
                ),
                (
                    "nric",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="NRIC must start with an alphabet character, followed by 3 digits, and ending with an alphabet character.",
                                regex="\\d{3}[A-Za-z]$",
                            ),
                            django.core.validators.MinLengthValidator(9),
                        ],
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            managers=[
                ("genericUserManager", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "eid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "eventName",
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("startDate", models.DateTimeField()),
                ("endDate", models.DateTimeField()),
                ("eventImage", models.ImageField(blank=True, upload_to="events/")),
                (
                    "eventStatus",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("over", "Over"),
                        ],
                        default="Open",
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "noVol",
                    models.IntegerField(default=0, verbose_name="Number of Volunteers"),
                ),
                (
                    "eventDesc",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(2)]
                    ),
                ),
            ],
            managers=[
                ("eventManager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NOK",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "phoneNum",
                    models.CharField(
                        max_length=8,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            managers=[
                ("adminManager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NormalUser",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("birthday", models.DateField()),
            ],
            managers=[
                ("normalUserManager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("validOrganisation", models.BooleanField(default=False)),
            ],
            managers=[
                ("organizerManager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.event"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.normaluser"
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "participant")},
            },
            managers=[
                ("eventParticipantManager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EventOrganizerMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approval",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reject", "Rejected"),
                            ("accepted", "Accepted"),
                        ],
                        default="pending",
                        max_length=12,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.event"
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.organizer"
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "organizer")},
            },
            managers=[
                ("eventMapperManager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContacts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nok",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.nok"
                    ),
                ),
                (
                    "normalUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.normaluser"
                    ),
                ),
            ],
            options={
                "unique_together": {("normalUser",)},
            },
        ),
    ]
