# Generated by Django 4.2.5 on 2023-10-12 10:07

import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="eventorganizermapping",
            managers=[
                ("eventMapperManager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventparticipant",
            managers=[
                ("eventParticipantManager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="eventImage",
            field=models.ImageField(blank=True, upload_to="events/"),
        ),
        migrations.AlterField(
            model_name="genericuser",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="genericuser",
            name="nric",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="NRIC must start with an alphabet character, followed by 8 digits, and ending with an alphabet character.",
                        regex="^[A-Za-z]\\d{7}[A-Za-z]$",
                    )
                ],
            ),
        ),
    ]
