# Generated by Django 4.2.5 on 2023-10-17 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_eventorganizermapping_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventStatus',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('over', 'Over')], default='Open', max_length=10, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
