# Generated by Django 4.2.5 on 2023-09-23 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_genericuser_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genericuser",
            old_name="phone",
            new_name="phoneNum",
        ),
    ]
