
version: "3.4"

networks:
  production:
    driver: bridge

services:
  database:
    image: mariadb
    container_name: backend_database_prod
    env_file: ./docker.env
    restart: always
    volumes:
      - ./backend/database:/var/lib/mysql
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 1m30s
      timeout: 5s
      retries: 10
      start_period: 5m
    networks:
      - production
  frontend:
    container_name: nextjs_frontend_prod
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm run dev
    ports:
      - "3000"
    environment:
      NODE_ENV: development
    restart: unless-stopped
    volumes:
      - ./frontend:/app/frontend
    networks:
      - production
  backend:
    container_name: django_backend_prod
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000"
    volumes:
      - ./backend:/app/backend
    env_file: ./docker.env
    command: bash -c "python manage.py migrate; if [[ $$? -ne 0 ]]; then sleep infinity; else python manage.py runserver 0.0.0.0:8000; fi"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    networks:
      - production
