version: "3.4"

services:
  database:
    image: mariadb
    container_name: backend_database
    env_file: ./docker.env
    restart: always
    volumes:
      - ./backend/database:/var/lib/mysql 
      - ./backend/script/CreateUser.sh:/CreateUser.sh
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 1m30s
      timeout: 5s
      retries: 10
      start_period: 5m
  frontend:
    container_name: nexjs_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm run dev
    ports:
      - "3000"
    environment:
      NODE_ENV: development
    restart: unless-stopped
    volumes:
      - ./frontend:/app/frontend
  backend:
    container_name: django_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000"
    volumes:
      - ./backend:/app/backend
    env_file: ./docker.env
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    command: bash -c "python manage.py migrate; if [[ $$? -ne 0 ]]; then sleep infinity; else python manage.py runserver 0.0.0.0:8000; fi"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
