version: '3.4'

services:
  frontend:
    container_name: nexjs_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app/frontend
  backend:
    container_name: django_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend