version: "3.4"

services:
  nginx:
    container_name: nginx_server
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/config:/etc/nginx/config
  jenkins:
    container_name: jenkins_container
    build:
      context: .
      dockerfile: ./jenkins/Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jenkins_home:/var/jenkins_home
    environment:
     - JENKINS_OPTS=--prefix=/jenkins --httpsPort=8443 
