version: "3.4"

networks:
  production:
    external: true
  jenkins_network:
    driver: bridge

services:
  nginx:
    container_name: nginx_server
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/config:/etc/nginx/config
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - production
      - jenkins_network
  jenkins:
    container_name: jenkins_container
    build:
      context: .
      dockerfile: ./jenkins/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jenkins_home:/var/jenkins_home
      - ./docker.env:/home/docker.env
      - ./frontend:/home/to_production/frontend
      - ./backend:/home/to_production/backend
      - ./docker-compose.yml:/home/to_production/docker-compose.yml
      - ./server-compose.yml:/home/to_production/server-compose.yml
      - ./requirements.txt:/home/to_production/requirements.txt
    environment:
     - JENKINS_OPTS=--prefix=/jenkins --httpsPort=8443 
    networks:
      - jenkins_network
