version: "3.4"

networks:
  production:
    external: true
  jenkins_network:
    driver: bridge

services:
  nginx:
    container_name: nginx_server
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/config:/etc/nginx/config
      - ./nginx/logs/production.access.log:/var/log/nginx/production.access.log
      - ./nginx/logs/production.error.log:/var/log/nginx/production.error.log
      - ./nginx/logs/jenkins.access.log:/var/log/nginx/jenkins.access.log
      - ./nginx/logs/jenkins.error.log:/var/log/nginx/jenkins.error.log
      - ./backend/mediafiles:/app/backend/mediafiles
      - ./backend/production_static:/app/backend/production_static
    depends_on:
      - backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - production
      - jenkins_network
  jenkins:
    container_name: jenkins_container
    build:
      context: .
      dockerfile: ./jenkins/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jenkins_home:/var/jenkins_home
      - ./docker.env:/home/docker.env
    environment:
     - JENKINS_OPTS=--prefix=/jenkins --httpsPort=8443 
    security_opt:
      - no-new-privileges:true
    networks:
      - jenkins_network
